package com.example.strawberry_app.screens.radioScreen
import com.example.strawberry_app.data.dao.StationWithStreams

val previewRadioScreenState = RadioScreenState(
    albumArtCollection = emptyMap(),
    radioState = RadioState(
        activeStation = "Groove Salad",
        activeStream = "https://ice2.somafm.com/groovesalad-256-mp3"
    ),
    stations = listOf(
        // SomaFM
        StationWithStreams(
            bitrate = 256,
            clickCount = 1500,
            country = "US",
            description = "A nicely chilled plate of ambient/electronica.",
            donate = "https://somafm.com/donate/",
            format = "mp3",
            genre = listOf("Ambient", "Electronica"),
            homepage = "https://somafm.com/groovesalad/",
            id = "groovesalad",
            image = "https://api.somafm.com/img/groovesalad120.png",
            language = "English",
            streamName = "Groove Salad",
            stationName = "Soma FM",
            quality = "High",
            stationSource = "somafm",
            stationUrl = "https://somafm.com/groovesalad/",
            streamUrl = "https://ice2.somafm.com/groovesalad-256-mp3",
            votes = 2500
        ),
        StationWithStreams(
            bitrate = 128,
            clickCount = 800,
            country = "US",
            description = "Ambient music for sleeping and relaxing.",
            donate = "https://somafm.com/donate/",
            format = "aac",
            genre = listOf("Ambient", "Sleep"),
            homepage = "https://somafm.com/dronezone/",
            id = "dronezone",
            image = "https://api.somafm.com/img/dronezone120.png",
            language = "English",
            streamName = "Drone Zone",
            stationName = "Soma FM",
            quality = "Medium",
            stationSource = "somafm",
            stationUrl = "https://somafm.com/dronezone/",
            streamUrl = "https://ice2.somafm.com/dronezone-128-aac",
            votes = 1200
        ),
        StationWithStreams(
            bitrate = 128,
            clickCount = 600,
            country = "US",
            description = "New sounds of the old west.",
            donate = "https://somafm.com/donate/",
            format = "mp3",
            genre = listOf("Country", "Americana"),
            homepage = "https://somafm.com/bootliquor/",
            id = "bootliquor",
            image = "https://api.somafm.com/img/bootliquor120.png",
            language = "English",
            streamName = "Boot Liquor",
            stationName = "Soma FM",
            quality = "Medium",
            stationSource = "somafm",
            stationUrl = "https://somafm.com/bootliquor/",
            streamUrl = "https://ice2.somafm.com/bootliquor-128-mp3",
            votes = 900
        ),
        // Radio Paradise
        StationWithStreams(
            bitrate = 320,
            clickCount = 3000,
            country = "US",
            description = "Eclectic rock, world and beyond.",
            donate = "https://radioparadise.com/donate",
            format = "mp3",
            genre = listOf("Eclectic", "Rock", "World"),
            homepage = "https://radioparadise.com",
            id = "rp_main",
            image = "https://radioparadise.com/graphics/logo.png",
            language = "English",
            streamName = "Radio Paradise Main",
            stationName = "Radio Paradise",
            quality = "High",
            stationSource = "radioparadise",
            stationUrl = "https://radioparadise.com",
            streamUrl = "https://stream.radioparadise.com/mp3-320",
            votes = 5000
        ),
        StationWithStreams(
            bitrate = 320,
            clickCount = 1200,
            country = "US",
            description = "Mellow mix of rock and world music.",
            donate = "https://radioparadise.com/donate",
            format = "mp3",
            genre = listOf("Mellow", "Rock"),
            homepage = "https://radioparadise.com",
            id = "rp_mellow",
            image = "https://radioparadise.com/graphics/logo_mellow.png",
            language = "English",
            streamName = "Radio Paradise Mellow Mix",
            stationName = "Radio Paradise",
            quality = "High",
            stationSource = "radioparadise",
            stationUrl = "https://radioparadise.com",
            streamUrl = "https://stream.radioparadise.com/mellow-320",
            votes = 2100
        ),
        StationWithStreams(
            bitrate = 320,
            clickCount = 900,
            country = "US",
            description = "Rock and metal mix.",
            donate = "https://radioparadise.com/donate",
            format = "mp3",
            genre = listOf("Rock", "Metal"),
            homepage = "https://radioparadise.com",
            id = "rp_rock",
            image = "https://radioparadise.com/graphics/logo_rock.png",
            language = "English",
            streamName = "Radio Paradise Rock Mix",
            stationName = "Radio Paradise",
            quality = "High",
            stationSource = "radioparadise",
            stationUrl = "https://radioparadise.com",
            streamUrl = "https://stream.radioparadise.com/rock-320",
            votes = 1800
        ),
        // RadioBrowser
        StationWithStreams(
            bitrate = 128,
            clickCount = 5000,
            country = "DE",
            description = "German public radio.",
            donate = "",
            format = "mp3",
            genre = listOf("Public", "News", "Talk"),
            homepage = "https://www.ndr.de",
            id = "ndr_info",
            image = "https://www.ndr.de/logo.png",
            language = "German",
            streamName = "NDR Info",
            stationName = "Radio Browser",
            quality = "Medium",
            stationSource = "radiobrowser",
            stationUrl = "https://www.ndr.de",
            streamUrl = "https://ndr-ndrinfo.cast.addradio.de/ndr/ndrinfo/story/mp3/128/stream.mp3",
            votes = 3200
        ),
        StationWithStreams(
            bitrate = 192,
            clickCount = 2200,
            country = "GB",
            description = "BBC Radio 6 Music.",
            donate = "",
            format = "mp3",
            genre = listOf("Alternative", "Indie", "Rock"),
            homepage = "https://www.bbc.co.uk/6music",
            id = "bbc_6music",
            image = "https://www.bbc.co.uk/6music/logo.png",
            language = "English",
            streamName = "BBC Radio 6 Music",
            stationName = "Radio Browser",
            quality = "High",
            stationSource = "radiobrowser",
            stationUrl = "https://www.bbc.co.uk/6music",
            streamUrl = "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
            votes = 4100
        ),
        StationWithStreams(
            bitrate = 128,
            clickCount = 1800,
            country = "FR",
            description = "French jazz radio.",
            donate = "",
            format = "aac",
            genre = listOf("Jazz"),
            homepage = "https://www.tsfjazz.com",
            id = "tsf_jazz",
            image = "https://www.tsfjazz.com/logo.png",
            language = "French",
            streamName = "TSF Jazz",
            stationName = "Radio Browser",
            quality = "Medium",
            stationSource = "radiobrowser",
            stationUrl = "https://www.tsfjazz.com",
            streamUrl = "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
            votes = 2800
        )
    ),
    stationSource = listOf("Soma FM", "Radio Paradise", "Radio Browser")
)